### ISSUE TITLE
Clarify that a default constructor is needed

### ISSUE THREAD

**Issue by debuglevel** [Jsondb/jsondb-core#11]
If no default constructor is given, calls to jsondb will fail with an ArrayOutOfBoundsException or an InstantiationException somewhere in a java.* package (during the XML serialization and deserialization step).

It would be nice to point out, that those POJOs have to be JavaBeans (and may be to clarify what a JavaBean is). It would be even better to check for a default constructor via reflection and throw a meaningful Exception.

**Comment by FarooqKhan** [comment]
Thanks i will try to fix this soon

**Comment by FarooqKhan** [comment]
I have updated the Jsondb.io website with the information about convention POJO must follow as you suggested.

Thanks

**Comment by FarooqKhan** [comment]
Please review and if this is what you expected mark this closed.

**Comment by debuglevel** [comment]
Nice, thank you! That should help :-)
