### ISSUE TITLE
LocalDateTime cannot be persisted

### ISSUE THREAD

**Issue by ruromero** [Jsondb/jsondb-core#13]
Hi,

Is there any way to persist `java.time.LocalDateTime`? 
I understand that the problem lays in the lack of a default constructor during the `deepCopy` phase.

```
java.lang.InstantiationException: java.time.LocalDateTime
Continuing ...
java.lang.RuntimeException: failed to evaluate: <unbound>=Class.new();
```

Thanks

**Comment by FarooqKhan** [comment]
Maybe i need to support AttributeConverter like functionality as described here for JPA: https://www.thoughts-on-java.org/persist-localdate-localdatetime-jpa/

**Comment by FarooqKhan** [comment]
I wish i had to time to implement this, If someone can implement this i will be glad to review and include it

**Comment by jansoren** [comment]
Hi,

Could this issue be solved with [jackson-modules-java8](https://github.com/FasterXML/jackson-modules-java8)?

```java

ObjectMapper mapper = new ObjectMapper()
   .registerModule(new ParameterNamesModule())
   .registerModule(new Jdk8Module())
   .registerModule(new JavaTimeModule()); // new module, NOT JSR310Module
```
