### ISSUE TITLE
Why the weird format?

### ISSUE THREAD

**Issue by scphantm** [Jsondb/jsondb-core#14]
I am looking at this thing closely and i found one critical thing that i really dislike and i wanted to know why you did it.  this line right here

https://github.com/Jsondb/jsondb-core/blob/ebcb67be47fdde6a953190775189a90115055a38/src/main/java/io/jsondb/JsonDBTemplate.java#L211

That line pretty much locks you into the idea that each collection is a non-standard json and you can never pretty print that json file.  I want to use this as a way to inject test data into a gradle build, and the ability to pretty print the collection files is a big deal for me.  

Why did you do it this way rather than a collection being an array of objects?  If it was an array of objects you could simply use jackson or gson to slurp up the entire file and all is well

**Comment by FarooqKhan** [comment]
@scphantm JsonDB actually treats it data as NDJSON for all the same reasons as [NDJSON](http://ndjson.org) format was created. At that time it was important for us to be able to process the .json files with tools similar to unix-style text processing tools and shell pipelines, NDJSON like format is easy in those cases.

At the time I created JsonDB i was not aware of the term NDJSON else i would have named it as such.

I see you are disappointed by this approach my apologies JsonDB is probably not a good fit for your need.

**Comment by scphantm** [comment]
Ah, i see.  Yea, we are passing on this one and going to give jsonPath a try as being able to export standard json arrays into our tests is more important.  Thanks for responding.
