### ISSUE TITLE
jsonDBTemplate.getCollection() not able to identify already existing collection

### ISSUE THREAD

**Issue by saisreenathk** [Jsondb/jsondb-core#16]
We are trying to use jsonDBTemplate.getCollection() to check the Json files are already created and during next run even though the collection exists in the directory it is not able to fetch it and when it tries to createCollection, we get the following error: collection already exists.

Meaning during creation time, JsonDB is able to identify that collection exists and but jsonDBTemplate.getCollection() is not able to fetch the collection.

We implemented Serialisation and ensured that serialVersionUID is unique, but still facing the issue,. Can you please help

**Comment by FarooqKhan** [comment]
is it possible for you to share some code? This part of the code is pretty stable, I am unable to understand the problem from your description. Also, share any exceptions you are getting.

**Comment by saisreenathk** [comment]
Hi Farooq, Thanks for your support, I was able to resolve the issue by enabling DEBUG level logging to print JsonDB logs. I will seek for any further support as required. I appreciate for making this utility open source.
