### ISSUE TITLE
is it possible to move common properties to base class

### ISSUE THREAD

**Issue by chethan-K** [Jsondb/jsondb-core#18]

**Comment by chethan-K** [comment]
public class BaseModel {

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss.SSS")
	private Timestamp createdAt;

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss.SSS")
	private Timestamp updatedAt;
}

@Document(collection = "user", schemaVersion = "1.0")
public class User extends BaseModel {

}

**Comment by chethan-K** [comment]
I have simply tried by extending!!
Getting below exception!! 

java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.get(TreeMap.java:278)
	at io.jsondb.CollectionMetaData.<init>(CollectionMetaData.java:103)
	at io.jsondb.CollectionMetaData.builder(CollectionMetaData.java:213)
	at io.jsondb.JsonDBTemplate.initialize(JsonDBTemplate.java:122)
	at io.jsondb.JsonDBTemplate.<init>(JsonDBTemplate.java:102)
	at io.jsondb.JsonDBTemplate.<init>(JsonDBTemplate.java:82)

**Comment by FarooqKhan** [comment]
JsonDB does not implement its own restrictions, it expects every model class is valid Java Bean.

"Every object that you wish to save in JsonDB must be a POJO (Plain Old Java Object) that satisfies the JavaBean programming conventions. Each object must implement either Serializable or Externalizable, must have a no-arg(default) constructor, and each of its properties(attributes) must have public setter and getter methods. The names of these methods must be as per the JavaBean naming conventions."

So if your class implements the Java Bean conventions it should work perfectly fine. What you have posted above does not implement the Java Bean Convention for sure.
