### ISSUE TITLE
Is is possible to have different json-files using the same document?

### ISSUE THREAD

**Issue by jansoren** [Jsondb/jsondb-core#21]
Hi :slightly_smiling_face:  

I have multiple collections that are using the same document. Is there any posibility to persist the different collections in different json-files? 

The reason why I want to use multiple json files is that the data in them is large and has nothing to do with each other.

**Comment by FarooqKhan** [comment]
Hi @jansoren,

JsonDB already has one actual file named as 'collectionname.json' per collection. Can you explain a bit more what actually you are trying to achive.

Thanks
Farooq

**Comment by FarooqKhan** [comment]
@jansoren i think this is not a issue i am going to close it, if you still think this is a issue please reopen it.
