### ISSUE TITLE
How to get sort and Limit data?

### ISSUE THREAD

**Issue by Tanvir6364** [Jsondb/jsondb-core#30]
Hello,
How can we get limit data like sql such as say within range from 1 - 10, then from 10-20 etc.

Also is there any way to get sorted data from the collection (as in order by etc)?

Thanks

**Comment by FarooqKhan** [comment]
Not at the moment, but this is a good feature to have. I could overload the find() methods to take a Comparator to sort by. The limit functionality could also be implemented.

I will try to implement this when i get some time. I would also be happy to incorporate a pull request from you if you would want to implement.

Thanks
Farooq

**Comment by vinczebalazs** [comment]
Hi! Has this been released?

**Comment by FarooqKhan** [comment]
Sort part is done checked in, but not released on maven central yet.
I am working the limit part. Its going to take some more time. I am implementing it as a slice feature similar to python|numpy so its taking a bit more time. This weekend i will probably be able to spend more time and finish it. By end of march i hope to finish this.

**Comment by FarooqKhan** [comment]
This feature is now complete and checked in. I have released a build on maven but this will take a few days before it is visible.

There will be two builds version 1.0.115-j8 and 1.0.115-j11, first is built using JDK8 and the second one is built using JDK 11.

Please test and let me know if there are any issues.
