### ISSUE TITLE
cannot access JsonDBTemplate

### ISSUE THREAD

**Issue by NightCrawlerX1** [Jsondb/jsondb-core#31]
Every time I try to connect my application it generates the same error.

> C:\Users\Thomaz\Desktop\Bot\src\main\java\bot\finn\discord\Main.java:15: error: cannot access JsonDBTemplate
import io.jsondb.JsonDBTemplate;
                ^
  bad class file: C:\Users\Thomaz\.gradle\caches\modules-2\files-2.1\io.jsondb\jsondb-core\1.0.115-j11\28dd0e74b2dfc45748de1a683b025a71913cc6fd\jsondb-core-1.0.115-j11.jar(io/jsondb/JsonDBTemplate.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by FarooqKhan** [comment]
This happens when you are trying to use jsondb.jar compiled with higher version of javac in a project that uses a lower version of javac.
Exactly for this reason I have started releases two versions please use the version 1.0.115-j8
