### ISSUE TITLE
Provide security contact info

### ISSUE THREAD

**Issue by ettisan** [Jsondb/jsondb-core#40]
I'd like to privately discuss a security topic with the maintainers, but there is no way to privately contact them.

Ideally an e-mail address and PGP key should be provided.

**Comment by FarooqKhan** [comment]
@ettisan you can connect with at my email: farooq_m_khan@yahoo.com
PGP Public key: https://keys.openpgp.org/search?q=farooq_m_khan%40yahoo.com

**Comment by ettisan** [comment]
in case you did you receive my mail (august 22nd), let me know
