### ISSUE TITLE
invalid json format

### ISSUE THREAD

**Issue by nothub** [Jsondb/jsondb-core#52]
A json file I generated with jsondb has multiple top-level values and thus (afaik) is not a valid json document.
Is there a way to configure jsondb to create entries under a single top-level value?

Example:
```json
{"schemaVersion":"1.0"}
{"id":"foo","nickname":"a","onlineTimeSeconds":0,"lastSeenMillis":0,"ignoreAfk":false,"movedToAfk":0}
{"id":"bar","nickname":"b","onlineTimeSeconds":0,"lastSeenMillis":0,"ignoreAfk":false,"movedToAfk":0}
{"id":"baz","nickname":"c","onlineTimeSeconds":0,"lastSeenMillis":0,"ignoreAfk":false,"movedToAfk":0}
```

**Comment by FarooqKhan** [comment]
JsonDB is desiged this way, each file is equivalent to a collection, and each entry is equivalent to one document. There is no way to make the entire file  a valid JSON document
